version: '3'

services:
    database:
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: devDB
            # You should definitely change the password in production
            POSTGRES_PASSWORD: devPasswd
            POSTGRES_USER: devUser
        restart: always
        ports:
            - "5432:5432"
        volumes:
            # - db-data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            - ./.docker/db/data:/var/lib/postgresql/data:rw